apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-lab-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Moon-5070/cilium-network-automation.git
    targetRevision: main
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
