#!/usr/bin/env python3
"""Monitor Hubble flows and enforce deny rules from declarative rule definitions."""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

POLICY_PATH = Path("policies/99-deny-google-generated.yaml")
VIOLATION_LOG_PATH = Path("logs/hubble_violations.log")
CILIUM_NAMESPACE = "kube-system"
CILIUM_LABEL_SELECTOR = "k8s-app=cilium"

RULES = [
    {
        "name": "deny-google-com",
        "source_namespace": "frontend",
        "destination": "google.com",
        "action": "deny",
    }
]


@dataclass(frozen=True)
class Rule:
    name: str
    source_namespace: str
    destination: str
    action: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply-immediately", action="store_true")
    parser.add_argument("--auto-push", action="store_true")
    return parser.parse_args()


def setup_logging() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def get_namespace(flow: dict[str, Any], endpoint_key: str) -> str | None:
    endpoint = flow.get(endpoint_key, {})
    if isinstance(endpoint, dict):
        ns = endpoint.get("namespace")
        if isinstance(ns, str):
            return ns
    return None


def load_rules() -> list[Rule]:
    return [Rule(**raw_rule) for raw_rule in RULES]


def _domain_matches(domain: str, target: str) -> bool:
    return domain == target or domain.endswith(f".{target}")


def flow_targets_domain(flow: dict[str, Any], target_domain: str) -> bool:
    l7 = flow.get("l7", {})
    if isinstance(l7, dict):
        dns = l7.get("dns", {})
        if isinstance(dns, dict):
            query = dns.get("query")
            if isinstance(query, str) and _domain_matches(query.rstrip('.'), target_domain):
                return True

    destination_names = flow.get("destinationNames", [])
    if isinstance(destination_names, list):
        for name in destination_names:
            if isinstance(name, str) and _domain_matches(name.rstrip('.'), target_domain):
                return True

    ip = flow.get("IP", {})
    if isinstance(ip, dict):
        dst = ip.get("destination")
        if isinstance(dst, str) and _domain_matches(dst.rstrip('.'), target_domain):
            return True

    return False


def match_rule(flow: dict[str, Any], rule: Rule) -> bool:
    src_ns = get_namespace(flow, "source")
    return src_ns == rule.source_namespace and flow_targets_domain(flow, rule.destination)


def render_policy_yaml(rule: Rule) -> str:
    return f"""# Generated by scripts/hubble_monitor.py
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {rule.name}
  namespace: {rule.source_namespace}
spec:
  endpointSelector: {{}}
  egressDeny:
    - toFQDNs:
        - matchName: {rule.destination}
        - matchPattern: "*.{rule.destination}"
"""


def write_policy(path: Path, rule: Rule) -> str:
    yaml = render_policy_yaml(rule)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml, encoding="utf-8")
    return yaml


def log_violation(flow: dict[str, Any], rule: Rule) -> None:
    VIOLATION_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "rule": rule.__dict__,
        "summary": flow.get("summary", "no summary"),
        "flow": flow,
    }
    with VIOLATION_LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def maybe_commit_and_push_policy(path: Path, auto_push: bool) -> None:
    subprocess.run(["git", "add", str(path)], check=True)
    has_staged_changes = subprocess.run(["git", "diff", "--cached", "--quiet"], check=False)
    if has_staged_changes.returncode == 0:
        logging.info("No staged changes for policy; skipping commit/push")
        return
    subprocess.run(["git", "commit", "-m", "chore(policy): update generated deny google policy"], check=True)
    if auto_push:
        subprocess.run(["git", "push"], check=True)


def apply_policy_now(path: Path) -> None:
    subprocess.run(["kubectl", "apply", "-f", str(path)], check=True)


def get_cilium_pod_name() -> str:
    cmd = ["kubectl", "-n", CILIUM_NAMESPACE, "get", "pods", "-l", CILIUM_LABEL_SELECTOR, "-o", "jsonpath={.items[0].metadata.name}"]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    pod_name = result.stdout.strip()
    if not pod_name:
        raise RuntimeError("No Cilium pod found")
    return pod_name


def monitor_flows(rules: list[Rule], apply_immediately: bool, auto_push: bool) -> None:
    seen_policy_digests: set[str] = set()
    cilium_pod = get_cilium_pod_name()
    cmd = ["kubectl", "-n", CILIUM_NAMESPACE, "exec", cilium_pod, "--", "hubble", "observe", "-o", "json"]
    with subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, bufsize=1) as proc:
        assert proc.stdout is not None
        for line in proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                flow = json.loads(line)
            except json.JSONDecodeError:
                continue
            for rule in rules:
                if rule.action != "deny" or not match_rule(flow, rule):
                    continue
                logging.warning("Violation detected for rule %s", rule.name)
                log_violation(flow, rule)
                policy_yaml = write_policy(POLICY_PATH, rule)
                digest = hashlib.sha256(policy_yaml.encode("utf-8")).hexdigest()
                if digest in seen_policy_digests:
                    continue
                seen_policy_digests.add(digest)
                maybe_commit_and_push_policy(POLICY_PATH, auto_push=auto_push)
                if apply_immediately:
                    apply_policy_now(POLICY_PATH)


def main() -> None:
    args = parse_args()
    setup_logging()
    rules = load_rules()
    try:
        monitor_flows(rules, apply_immediately=args.apply_immediately, auto_push=args.auto_push)
    except (FileNotFoundError, subprocess.CalledProcessError, RuntimeError) as exc:
        logging.error("Monitor failed: %s", exc)
        raise SystemExit(1) from exc
    except KeyboardInterrupt:
        logging.info("Stopped by user")


if __name__ == "__main__":
    main()
