from __future__ import annotations

import datetime
import json
import logging
import subprocess
from pathlib import Path
from typing import Any

FRONTEND_NAMESPACE = "frontend"
DATABASE_NAMESPACE = "database"
POLICY_PATH = Path("policies/99-deny-frontend-to-database-generated.yaml")
CILIUM_NAMESPACE = "kube-system"
CILIUM_LABEL_SELECTOR = "k8s-app=cilium"


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )


def get_namespace(flow: dict[str, Any], endpoint_key: str) -> str | None:
    endpoint = flow.get(endpoint_key, {})
    if isinstance(endpoint, dict):
        namespace = endpoint.get("namespace")
        if isinstance(namespace, str):
            return namespace
    return None


def is_frontend_to_database(flow: dict[str, Any]) -> bool:
    src_ns = get_namespace(flow, "source")
    dst_ns = get_namespace(flow, "destination")
    return src_ns == FRONTEND_NAMESPACE and dst_ns == DATABASE_NAMESPACE


def generate_deny_policy(path: Path) -> None:
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
    yaml = f"""# Generated by scripts/hubble_monitor.py at {timestamp}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-frontend-to-database
  namespace: {FRONTEND_NAMESPACE}
spec:
  endpointSelector: {{}}
  egressDeny:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {DATABASE_NAMESPACE}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml, encoding="utf-8")


def get_cilium_pod_name() -> str:
    cmd = [
        "kubectl",
        "-n",
        CILIUM_NAMESPACE,
        "get",
        "pods",
        "-l",
        CILIUM_LABEL_SELECTOR,
        "-o",
        "jsonpath={.items[0].metadata.name}",
    ]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    pod_name = result.stdout.strip()
    if not pod_name:
        raise RuntimeError(
            f"No Cilium pod found in namespace '{CILIUM_NAMESPACE}' with label '{CILIUM_LABEL_SELECTOR}'."
        )
    return pod_name


def monitor_flows() -> None:
    cilium_pod = get_cilium_pod_name()
    cmd = [
        "kubectl",
        "-n",
        CILIUM_NAMESPACE,
        "exec",
        cilium_pod,
        "--",
        "hubble",
        "observe",
        "-o",
        "json",
    ]
    logging.info("Starting flow monitor via cilium pod %s", cilium_pod)

    with subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    ) as proc:
        assert proc.stdout is not None

        for line in proc.stdout:
            line = line.strip()
            if not line:
                continue

            try:
                flow = json.loads(line)
            except json.JSONDecodeError:
                logging.debug("Skipping non-JSON line: %s", line)
                continue

            if is_frontend_to_database(flow):
                logging.warning(
                    "Detected frontend -> database flow: %s",
                    flow.get("summary", "no summary"),
                )
                generate_deny_policy(POLICY_PATH)
                logging.info("Wrote deny policy: %s", POLICY_PATH)

        return_code = proc.wait()
        if return_code != 0:
            err = proc.stderr.read() if proc.stderr else ""
            raise RuntimeError(
                f"kubectl exec hubble observe exited with code {return_code}: {err.strip()}"
            )


def main() -> None:
    setup_logging()
    try:
        monitor_flows()
    except FileNotFoundError as exc:
        logging.error("Failed to run required command: %s", exc)
        raise SystemExit(1) from exc
    except subprocess.CalledProcessError as exc:
        logging.error("Failed to discover Cilium pod: %s", exc.stderr.strip())
        raise SystemExit(1) from exc
    except KeyboardInterrupt:
        logging.info("Stopped by user")


if __name__ == "__main__":
    main()
